currentimage_scaled;
figure;
imagesc(reshape(image(:,:,1),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=1 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_1-slice_img01_a150.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,1),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=1 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_1-slice_img01_a150.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,6),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=6 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_6-slice_img01_a150.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,6),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=6 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_6-slice_img01_a150.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,12),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=12 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_12-slice_img01_a150.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,12),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=12 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_12-slice_img01_a150.png;

