currentimage_scaled;
figure;
imagesc(reshape(image(:,:,1),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=1 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_1-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,1),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=1 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_1-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,2),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=2 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_2-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,2),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=2 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_2-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,3),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=3 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_3-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,3),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=3 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_3-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,4),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=4 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_4-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,4),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=4 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_4-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,5),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=5 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_5-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,5),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=5 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_5-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,6),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=6 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_6-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,6),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=6 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_6-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,7),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=7 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_7-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,7),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=7 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_7-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,8),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=8 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_8-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,8),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=8 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_8-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,9),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=9 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_9-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,9),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=9 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_9-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,10),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=10 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_10-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,10),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=10 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_10-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,11),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=11 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_11-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,11),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=11 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_11-slice_img02_a90.png;

currentimage_scaled;
figure;
imagesc(reshape(image(:,:,12),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Unconditional image slice=12 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng currentimage_scaled_12-slice_img02_a90.png;
conditionedimage_scaled;
figure;
imagesc(reshape(image(:,:,12),40,60));
#ax=gca();
#set (ax, "xtick", );
#set (ax, "xticklabel", ); 
#set (ax, "ytick", );
#set (ax, "yticklabel", ); 
title("Conditional image slice=12 (scaled)","fontsize",26);
xlabel("X","fontsize",20);
ylabel("Y","fontsize",20);
caxis([ -2 , 4 ]);
colorbar();
axis("xy");
print -dpng conditionedimage_scaled_12-slice_img02_a90.png;

